[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dipd"
version = "0.0.1"
authors = [
  { name="Gunnar König", email="g.koenig.edu@pm.me" },
  { name="Eric Günther", email="eric.guenther@uni-tuebingen.de" },
]
description = "Disentangling Interactions and Dependencies (DIP) Decomposition."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "numpy",
  "pandas",
  "interpret>=0.7.6,<0.8.0",
  "matplotlib",
  "seaborn",
  "tqdm",
  "scikit-learn",
  "statsmodels",
]

[tool.hatchling.build]
exclude = [
  "**/__pycache__",
  "**/*.pyc",
  "**/*.pyo",
]

[project.urls]
Homepage = "https://github.com/gcskoenig/dipd"
Issues = "https://github.com/gcskoenig/dipd/issues"

